masifapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import logout
from django.urls import path, include

from masifapp import settings

urlpatterns = [
    path('', include('landing.urls')),
    path('cari-lowongan/', include('cari_lowongan.urls')),
    path('admin/', include('admin.urls')),
    path('opd/', include('opd.urls')),
    path('lowongan/', include('lowongan.urls')),
    path('account-redirector', include('account_redirector.urls')),
    path('superuser/', admin.site.urls),
    #     # path('auth/', include('social_django.urls')),
    #     # TESTING PATH dibawah ini
    #     path('user/', include('google_oauth2.urls')),
    path('user/', include('user.urls')),
    path('kesbangpol/', include('kesbangpol.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

opd/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from opd.opd_login_form import OpdAuthenticationForm

from . import views

urlpatterns = [
    path('', views.opd_home, name='opd_home'),
    path('lowongan/buka-tutup/<str:id_lowongan>/', views.opd_tutup_lowongan, name='opd_tutup_lowongan'),
    path('proses-<str:id_user>-<str:id_lowongan>/<str:status>/<str:catatan>/' , views.opd_update_lamaran , name = 'opd_update_lamaran'),
    path('lowongan/file_tambahan-<str:id_user>-<str:id_lowongan>/' , views.opd_download_file , name = 'opd_download_file'),
    path('lowongan/cv_pendaftar-<str:id_user>-<str:id_lowongan>/' , views.opd_download_cv , name = 'opd_download_cv'),
    path('lowongan/list-pendaftar-<str:id_lowongan>/', views.opd_list_pendaftar, name='opd_list_pendaftar'),
    path('lowongan/detail-<str:id_lowongan>/', views.opd_detail_lowongan, name='opd_detail_lowongan'),
    path('login/', LoginView.as_view(template_name='opd_login.html',form_class=OpdAuthenticationForm,),name='opd_login'),
    path('verification/404', views.opd_verification_not_found,
         name='opd_verification_not_found'),
    path('verification/<str:token>',
         views.opd_verification, name='opd_verification'),
    path('verification/',
         views.opd_verification_redirect, name='opd_verification_redirect'),
     
]

user/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path, include

from . import views
from .user_login_form import UserAuthenticationForm

urlpatterns = [
    path('dashboard/', views.user_dashboard, name='user_dashboard'),
    path('dashboard/edit/', views.user_edit_profile, name='user_edit_profile'),
    path('dashboard/edit/upload_cv/', views.upload_cv, name='user_edit_upload_cv'),
    path('dashboard/edit/upload_profile_picture/', views.upload_profile_picture, name='user_edit_upload_pp'),
    path('dashboard/edit/delete_cv/', views.delete_cv, name='delete_cv'),
    path('dashboard/api/get-all-lamaran-for-dashboard-table/', views.get_all_lamaran_for_dashboard_table,
         name='get_all_lamaran_for_dashboard_table'),
    path('register/', views.user_register, name='user_register'),
    path(
        'login/',
        LoginView.as_view(
            template_name='user_login.html',
            form_class=UserAuthenticationForm, ),
        name='user_login'),
    path('verification/404', views.user_verification_not_found,
         name="user_verification_not_found"),
    path('verification/<str:token>', views.user_verification,
         name="user_verification"),
    path('verification/', views.user_verification_redirect,
         name="user_verification_redirect"),
    path('auth/', include('social_django.urls', namespace='social')),
    path('dashboard/status-lamaran/<int:id_user_lamar_magang>/', views.user_see_status_lamaran,
         name='user_see_status_lamaran'),
]

account/models.py
from datetime import datetime

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models


class AccountManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError("Users must have email address")

        user = self.model(email=self.normalize_email(email))
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        if not email:
            raise ValueError("Users must have email address")

        user = self.create_user(
            email=self.normalize_email(email),
            password=password)
        user.name = "SuperUser"
        user.phone = "000"
        user.is_superuser = True
        user.is_admin = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    profile_picture = models.FileField(
        null=True,
        blank=True,
    )
    name = models.CharField(max_length=128)
    email = models.EmailField(
        verbose_name="email", max_length=254, unique=True)
    phone = models.CharField(max_length=26)
    date_joined = models.DateTimeField(
        verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_superuser = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_kesbangpol = models.BooleanField(default=False)
    is_opd = models.BooleanField(default=False)
    is_user = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'

    objects = AccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return True


class OpdProfile(models.Model):
    user = models.OneToOneField(
        Account,
        on_delete=models.CASCADE,
        primary_key=True, null=False, blank=False
    )
    # Temporary Attribute
    unique_opd_attribute = models.CharField(max_length=60)

    def __str__(self):
        return "<OPD Profile> {}".format(self.unique_opd_attribute)


class AdminProfile(models.Model):
    user = models.OneToOneField(
        Account,
        on_delete=models.CASCADE,
        primary_key=True, null=False, blank=False
    )
    # Temporary Attribute
    unique_admin_attribute = models.CharField(max_length=60)

    def __str__(self):
        return "<ADMIN Profile> {}".format(self.unique_admin_attribute)


class UserProfile(models.Model):
    DEFAULT_NOT_SET = 'Not set'

    user = models.OneToOneField(
        Account,
        on_delete=models.CASCADE,
        primary_key=True,
        null=False,
        blank=False,
    )

    born_date = models.DateField(default=datetime(1945, 8, 17))
    born_city = models.CharField(default=DEFAULT_NOT_SET, max_length=120)
    address = models.CharField(default=DEFAULT_NOT_SET, max_length=300)
    '''
    *sex types*
    m = male
    f = female
    n = not set
    '''
    sex = models.CharField(default='n', max_length=1)
    education = models.CharField(default=DEFAULT_NOT_SET, max_length=120)
    institution = models.CharField(default=DEFAULT_NOT_SET, max_length=120)
    major = models.CharField(default=DEFAULT_NOT_SET, max_length=120)
    cv = models.FileField(
        null=True,
        blank=True,
    )
    # Temporary Attribute
    unique_pelamar_attribute = models.CharField(max_length=60, default='a')

    def __str__(self):
        return "<USER Profile> Account : {}".format(self.user.email)


class PelamarProfile(models.Model):
    user = models.OneToOneField(
        Account,
        on_delete=models.CASCADE,
        primary_key=True, null=False, blank="False"
    )
    # Temporary Attribute
    unique_pelamar_attribute = models.CharField(max_length=60)

    def __str__(self):
        return "<PELAMAR Profile> {}".format(self.unique_pelamar_attribute)

class KesbangpolProfile(models.Model):
    user = models.OneToOneField(
        Account,
        on_delete=models.CASCADE,
        primary_key=True, null=False, blank=False
    )
    # Temporary Attribute
    unique_kesbangpol_attribute = models.CharField(max_length=60)

    def __str__(self):
        return "<KESBANGPOL Profile> {}".format(
            self.unique_kesbangpol_attribute)

user/models.py
from django.db import models


class UserVerificationList(models.Model):
    secret = models.CharField(max_length=50, unique=True)
    name = models.CharField(max_length=30)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=20)
    password = models.CharField(max_length=50)
    creation_date = models.DateTimeField(
        verbose_name='creation date', auto_now_add=True)

user/forms.py
from django import forms

from account.models import UserProfile, Account


class EditUserProfileForm(forms.Form):
    string_field = forms.TextInput(
        attrs={
            'class': 'form-control',
            'type': 'text',
            'placeholder': 'Nama',
        }
    )

    date_field = forms.TextInput(
        attrs={
            'class': 'datepicker',
            'autocomplete': 'off'

        }
    )

    text_area_field = forms.Textarea(
        attrs={
            'class': 'form-control',
            'type': 'text',
        }
    )

    name = forms.CharField(
        max_length=100,
        min_length=1,
        widget=string_field,
    )
    string_field.attrs['placeholder'] = 'Kota lahir'
    born_city = forms.CharField(
        max_length=100,
        min_length=1,
        widget=string_field,
    )

    born_date = forms.CharField(widget=date_field)

    string_field.attrs['placeholder'] = 'Alamat'
    address = forms.CharField(
        max_length=300,
        min_length=1,
        widget=text_area_field,
    )
    sex = forms.ChoiceField(choices=[('m', 'Laki - Laki'), ('f', 'Perempuan')], widget=forms.Select(attrs={
        'class': 'form-control',
    }))

    string_field.attrs['placeholder'] = 'Pendidikan'
    education = forms.ChoiceField(choices=[
        ('s1', 'S1'),
        ('d4', 'D4'),
        ('d3', 'D3'),
        ('d1', 'D2'),
        ('d1', 'D1'),
        ('smk', 'SMK'),
        ('sma', 'SMA'),
    ],
        widget=forms.Select(attrs={
            'class': 'form-control',
        }))

    string_field.attrs['placeholder'] = 'Institusi'
    institution = forms.CharField(
        max_length=100,
        min_length=1,
        widget=string_field,
    )

    string_field.attrs['placeholder'] = 'Jurusan'
    major = forms.CharField(
        max_length=100,
        min_length=1,
        widget=string_field,
    )

    phone_field = forms.TextInput(
        attrs={
            'class': 'form-control',
            'type': 'text',
            'pattern': '^\+?1?\d{3,15}$',
            'placeholder': 'Nomor telepon',
        }
    )

    phone = forms.CharField(
        max_length=100,
        min_length=1,
        widget=phone_field,
    )


class CVForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('cv',)


class ProfilePictureForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('profile_picture',)
        widgets = {
            'profile_picture': forms.FileInput(attrs={'class': 'black'}),
        }

templates/user/pop_up_login.html
{#{% load static %}#}
{##}
{#<div class="modal fade" id="pop-up-login" tabindex="-1" role="dialog"#}
{#     aria-labelledby="exampleModalCenterTitle" aria-hidden="true">#}
{#    <div class="modal-dialog modal-dialog-centered" role="document">#}
{#        <div class="modal-content">#}
{#            <div class="modal-header">#}
{#                <h5 class="modal-title" id="exampleModalLongTitle">Masuk ke MASIF sebagai kandidat</h5>#}
{#                <button type="button" class="close" data-dismiss="modal" aria-label="Close">#}
{#                    <span aria-hidden="true">&times;</span>#}
{#                </button>#}
{#            </div>#}
{#            <div class="modal-body">#}
{#                <form>#}
{#                    <div style="text-align: center">#}
{#                        <div class="form-group">#}
{#                            <input type="email" class="form-control" id="exampleInputEmail1"#}
{#                                   aria-describedby="emailHelp" placeholder="Username/Email"#}
{#                                   style="width: 300px; display: inline">#}
{#                        </div>#}
{#                        <div class="form-group">#}
{#                            <input type="password" class="form-control" id="exampleInputPassword1"#}
{#                                   placeholder="Password" style="width: 300px; display: inline">#}
{#                        </div>#}
{#                    </div>#}
{#                    <div style="text-align: center">#}
{#                        <div>#}
{#                            <button type="submit" class="btn btn-primary" style="width: 300px">Masuk#}
{#                            </button>#}
{#                        </div>#}
{#                        <div style="padding: 1rem">#}
{#                            atau#}
{#                        </div>#}
{#                        <div>#}
{#                            <a href="{% url 'social:begin' 'google-oauth2' %}" id="google_login">#}
{#                                <img src="{% static 'img/btn_google_sign_in.png' %}" style="width: 200px" alt="oauth">#}
{#                            </a>#}
{#                        </div>#}
{#                    </div>#}
{#                </form>#}
{#            </div>#}
{#            <div style="text-align: center">#}
{#                <p>#}
{#                    Belum punya akun? <a href="/"><u>Buat disini</u></a><br>#}
{#                    <a href="/"><u>Lupa password?</u></a><br>#}
{#                </p>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</div>#}

templates/user/user-dashboard.html
{% extends 'base.html' %}

{% block head %}
    <link rel="stylesheet" href="/static/css/user/user-dashboard.css">

    <!-- DataTables -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">

    <script type="text/javascript" charset="utf8"
            src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>

    <title>Dashboard</title>
{% endblock %}


{% block body %}
    {% include 'navbar-no-bootstrap.html' %}
    <div class="container">
        {% include 'user/user-profile-detail-dashboard.html' %}

        <div class="row">
            <div class="col-12 col-sm-2">
                <h4>CV</h4>
            </div>
            <div class="col-12 col-sm-10">
                {% if user.userprofile.cv %}


                    <div id="cv-file-name"><a href="/media/{{ user.userprofile.cv }}">{{ user.userprofile.cv }}</a>
                    </div>

                    <button class="btn btn-primary" onclick="click_upload_cv()">Ubah CV</button>
                    <button id="delete-cv-button" type="button" class="btn btn-danger" data-toggle="modal"
                            data-target="#delete-cv-modal">
                        Hapus CV
                    </button>




                {% else %}
                    <p>Anda belum menambahkan CV</p>
                    <button class="btn btn-primary" onclick="click_upload_cv()">Unggah CV</button>


                {% endif %}

            </div>
        </div>


        <form id="form-cv" method="post" enctype="multipart/form-data" action="{% url 'user_edit_upload_cv' %}">
            {% csrf_token %}
            <span style="display: none">{{ form_cv.cv }}</span>
        </form>

        <table id="daftar-lamaran-table" class="display shadow bg-white mb-5" style="width:100%" aria-hidden="true">
            <thead>
            <tr>
                <td id="daftar-lamaran-title" colspan="3">Daftar Lamaran</td>
            </tr>
            <tr>
                <th scope="col">Status</th>
                <th scope="col">Posisi</th>
                <th scope="col">Kantor</th>
            </tr>
            </thead>
            <tbody>

            <tr>
                <td> Ditolak</td>
                <td> Programmer</td>
                <td> Diskominfo Depok</td>
            </tr>
            </tbody>
            <tfoot>
            </tfoot>
        </table>


        <!-- Modal -->
        <div class="modal fade" id="delete-cv-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Hapus CV</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Yakin Hapus CV?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
                        <button type="button" id="yes-delete-cv" class="btn btn-primary" onclick="deleteCVButton()"
                                data-dismiss="modal">Ya
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script>
        function deleteCVButton() {
            var token = '{{ csrf_token }}';
            $.ajax(
                {
                    url: '{% url 'delete_cv' %}',
                    type: 'post',
                    headers: {"X-CSRFToken": token},
                }
            );
            location.reload();

        }

        $(document).ready(function () {
            $('#daftar-lamaran-table').DataTable({
                "ajax": '/user/dashboard/api/get-all-lamaran-for-dashboard-table/'
            });
            {#$('#daftar-lamaran-table').wrap('<div id="daftar-lamaran-wrapper" class="shadow bg-white rounded"></div>');#}


        });


        function click_upload_cv() {
            $('#id_cv').click();
        }


        document.getElementById("id_cv").onchange = function () {
            document.getElementById("form-cv").submit();
        };

        document.getElementById("id_profile_picture").onchange = function () {
            document.getElementById("form-profile-picture").submit();
        };


    </script>

{% endblock %}

templates/user/user-edit-profile.html
{% extends 'base.html' %}

    {% block head %}
    <link rel="stylesheet" href="/static/css/bootstrap-datepicker3.standalone.min.css">
    <script src="/static/js/bootstrap-datepicker.min.js"></script>

    <title>Edit Profile</title>
    {% endblock %}

<body>

{% block body %}
    {% include 'navbar-no-bootstrap.html' %}
<div class="container">
<br>
    <div class="row">
        <div class="col-2">

        </div>


        <div class="col-8">
            <form action="{% url 'user_edit_profile' %}" method="post">
                {% csrf_token %}

                <div class="form-group">
                    <label>Nama </label>
                    {{ form.name }}
                </div>

                <div class="form-group">
                    <label>Kota Lahir </label>
                    {{ form.born_city }}
                </div>

                <div class="form-group">
                    <label>Tanggal Lahir </label><br>
                    {{ form.born_date }}
                </div>

                <div class="form-group">
                    <label>Alamat </label>
                    {{ form.address }}
                </div>

                <div class="form-group">
                    <label>Jenis Kelamin </label>
                    {{ form.sex }}
                </div>

                <div class="form-group">
                    <label>Pendidikan </label>
                    {{ form.education }}
                </div>

                <div class="form-group">
                    <label>Asal Institusi </label>
                    {{ form.institution }}
                </div>

                <div class="form-group">
                    <label>Jurusan </label>
                    {{ form.major }}
                </div>

                <div class="form-group">
                    <label>Nomor Telepon </label>
                    {{ form.phone }}
                </div>


                <label>Email : </label>
                {{ request.user.email }}
                <br>
                <br>
                <input type="submit" class="btn btn-primary" value="Ubah Profil">


            </form>
        </div>
        <div class="col-2">

        </div>
    </div>

</div>
<script>

    $('.datepicker').datepicker({
        format: 'dd/mm/yyyy',
        startView: 2,
        startDate: '1/1/1900',
        endDate: 'today',
        autoclose: true,
    });

</script>
    <br>
{% endblock %}
</body>
</html>

templates/user/user-lamaran-state.html
{% extends 'base.html' %}
{% block head %}
    <link rel="stylesheet" href="/static/css/user/user-lamaran-state.css">
    <title>Status Lamaran</title>
{% endblock %}
{% block body %}
    {% include 'navbar-no-bootstrap.html' %}

    <div class="container">
        {% include 'user/user-profile-detail-dashboard.html' %}
        <div id="top-detail-wrapper">
            <span id="top-detail-id" class="lamaran-top-detail">ID Lamaran : {{ lamaran_obj.pk }}</span>
            <span id="top-detail-posisi" class="lamaran-top-detail">{{ lamaran_obj.lowongan_foreign_key.judul }}</span>
            <span id="top-detail-opd"
                  class="lamaran-top-detail">{{ lamaran_obj.lowongan_foreign_key.opd_foreign_key.name }}</span></div>
        <!-- class .info-horizontal-separator is in static/css/user/user-profile-detail-dashboard.css -->
        <div class="info-horizontal-separator"></div>
        <div class="row lamaran-info-row">
            <div class="col-12 col-md-2">
                <h5>Application Letter</h5>
            </div>
            <div class="col-12 col-md-10">
                <p style="white-space: pre-line;">{{ lamaran_obj.application_letter }}</p>

            </div>
        </div>

        <div class="row lamaran-info-row">
            <div class="col-12 col-md-2">
                <h5>Berkas Unggahan</h5>
            </div>
            <div class="col-12 col-md-10">

                <a href="/media/{{ lamaran_obj.file_berkas_tambahan }}">{{ lamaran_obj.file_berkas_tambahan }}</a>

            </div>
        </div>

        <div class="row lamaran-info-row">
            <div class="col-12 col-md-2">
                <h5>Status Lamaran</h5>
            </div>
            <div class="col-12 col-md-2">
                <div class="state-text-wrapper">
                    {{ lamaran_obj.status_lamaran }}
                </div>

            </div>
        </div>

        <div class="row lamaran-info-row">
            <div class="col-12 col-md-2">
                <h5>Catatan</h5>
            </div>
            <div class="col-12 col-md-10">
                <p style="white-space: pre-line;">{{ lamaran_obj.notes_status_lamaran }}</p>

            </div>
        </div>

    </div>


{% endblock %}

templates/user/user-profile-detail-dashboard.html
<link rel="stylesheet" href="/static/css/user/user-profile-detail-dashboard.css">

<br>
<div class="row justify-content-start">

    <div id="profile-picture-col" class="col-12 col-sm-auto">
        <div class="image-upload">
            <label for="id_profile_picture">
                {% if user.profile_picture %}
                    <img style="image-orientation: flip;" id="profile_picture"
                         src="/media/{{ user.profile_picture }}">
                {% else %}
                    <img id="profile_picture" src="/static/img/add_photo.png">
                {% endif %}

            </label>
            <form id="form-profile-picture" method="post" enctype="multipart/form-data"
                  action="{% url 'user_edit_upload_pp' %}">
                {% csrf_token %}
                <span style="display: none">{{ form_pp.profile_picture }}</span>

            </form>

        </div>
    </div>
    <div id="user-info-col" class="col-12 col-sm-auto align-self-center">
        <span id="username">{{ user.name }}</span>
        <br>
        <span class="user-info-right-of-photo">{{ user.userprofile.education|title }}</span>
        <br>
        <span class="user-info-right-of-photo">{{ user.userprofile.institution }}</span>
        <br>
        <span class="user-info-right-of-photo phone-only">{{ user.phone }}</span>
        <br>
        <span class="user-info-right-of-photo phone-only">{{ user.email }}</span>
        <br>
        <span class="user-info-right-of-photo phone-only">{{ user.userprofile.address }}</span>

    </div>


</div>


<button class="btn btn-outline-primary" onclick="window.location.href = '{% url 'user_edit_profile' %}'">Edit
    Profil
</button>

<span class="widescreen-only">
        <div class="row">
            <div id="info-row-item-phone" class="col-12 col-sm-4 info-row-item">{{ user.phone }}</div>
            <div class="col-12 col-sm-4 info-row-item">{{ user.email }}</div>
            <div class="col-12 col-sm-4 info-row-item">{{ user.userprofile.address }}</div>
        </div>
    </span>
<div class="info-horizontal-separator"></div>

templates/user/user_register.html
{% extends 'base.html' %}
{% block head %}
    <style>
        #submit-btn {
            width: 100%
        }
    </style>
    <title>Daftar Pelamar</title>
{% endblock %}
{% block body %}
    {% include 'navbar-no-bootstrap.html' %}
    <div class="container-fluid">
        <div class="row justify-content-center" style="height: 100vh">
            <div class="col-4 align-self-center">
                {% for message in err %}
                    <div class="alert alert-danger" role="alert">
                        {{ message }}
                    </div>
                {% endfor %} 
                <form method="POST" action="{% url 'user_register' %}"
                      oninput='id_confirm_password.setCustomValidity(id_confirm_password.value != id_password.value ? "Passwords do not match." : "")'
                >
                    {% csrf_token %}
                    <h1 class="admin-login-items text-center">Pembuatan Akun Pelamar</h1>
                    <label>Nama : </label>
                    {{ form.user_name }}
                    <label>Email : </label>
                    {{ form.email }}
                    <label>Telepon : </label>
                    {{ form.phone }}
                    <label>Password : </label>
                    {{ form.password }}
                    <label>Konfirmasi Password : </label>
                    {{ form.confirm_password }}

                    <br>
                    <button type="submit" class="btn btn-primary admin-login-items" id="submit-btn">Submit</button>

                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/user_verification_404.html
<!DOCTYPE html>
<html lang="en">
<head>

    <style>
        #submit-btn {
            width: 100%
        }

        .admin-login-items {
            margin-bottom: 2em;
        }

        .opd-name {
            margin-bottom: 15px;
        }
    </style>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Verifikasi User</title>
</head>
<body>
<div class="container-fluid">
    <div class="row justify-content-center" style="height: 100vh">
        <div class="col-4 align-self-center">
            <h1>Token not found,<a href="/"> Please contact admin</a></h1>
        </div>
    </div>
</div>
</body>
</html>